name: Wyoming Cloud Streamer
slug: wyoming_cloud_streamer
version: "0.0.12"
description: Wyoming server for cloud TTS providers (streaming)
arch: [amd64, aarch64, armv7, armhf, i386]
init: false
startup: application
boot: auto
ingress: false
host_network: false
ports:
  "10200/tcp": 10200
map:
  - config:rw

arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386

schema:
  openai_model: str? 
  openai_api_key: password?
  openai_base_url: str?
  speaking_rate: float?
  openai_voices: str?
  openai_languages: str?

options:
  openai_model: "gpt-4o-mini-tts"
  openai_api_key: ""
  openai_base_url: ""
  speaking_rate: 1.0
  openai_voices: ""
  openai_languages: ""
