[project]
name = "wyoming-openai-streamer"
version = "0.1.1"
description = "Wyoming protocol server for cloud OpenAI or local OpenAIcompatible TTS providers (streaming)."
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "Michael Hansen", email = "mike@rhasspy.org"},
    {name = "jarneson33", email = "arneson33@gmail.com"}
]
keywords = ["rhasspy", "wyoming", "openai", "tts"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Text Processing :: Linguistic",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "wyoming>=1.10.0,<2.0.0",
    "regex==2026.7.19",
    "sentence-stream==1.3.0",
    "openai>=3.3.1,<4.0.0"
]

[project.urls]
Homepage = "https://github.com/jarneson33/wyoming-openai-streamer"

[project.scripts]
wyoming-openai-streamer = "wyoming_openai_streamer.__main__:run"

[tool.setuptools.packages.find]
include = ["wyoming_openai_streamer"]

[build-system]
requires = ["setuptools>=84.0.0", "wheel>=0.48.0"]
build-backend = "setuptools.build_meta"

